# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdfef6e5522ead2c810b53b202153753f571bb69a6040b88c34b285c97bac2c88669a0e85beab3c8f5255d2341e6710f2ad25760980eb6ac88164f60c1879639
  aws_secret_key : qwertyytrewq

test:
  secret_key_base: d773e16ab0b5147f8687205b6d445ff0bf97f53b58467a919600f68cc75f1721a57b77bfed918c07e5380b6d59f19edcaacce2a6752fdf7506cc64324a95a96b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
